# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cidr < Formula
  desc "CLI tool for checking IPs against CIDR blocks"
  homepage "https://clokwork.net/cidr/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/clok/cidr/releases/download/v0.1.0/cidr_0.1.0_darwin_arm64.tar.gz"
      sha256 "cd439b3fd659d3a6302cd4ecbb2d2ca311a53632201d2755888e6d64b4f5355f"

      def install
        bin.install "cidr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clok/cidr/releases/download/v0.1.0/cidr_0.1.0_darwin_amd64.tar.gz"
      sha256 "ebd7540e67709ceadad17ceb2907609d2f3d39dc0f8519acad2d8ce8b78fbf94"

      def install
        bin.install "cidr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clok/cidr/releases/download/v0.1.0/cidr_0.1.0_linux_armv6.tar.gz"
      sha256 "7a9d414e75c94490b7ea0e7bf831c99954934768d128262ba6ee4ac9c246160f"

      def install
        bin.install "cidr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clok/cidr/releases/download/v0.1.0/cidr_0.1.0_linux_amd64.tar.gz"
      sha256 "c01bbbb9cf8690cc2a11e83711b624a0a1e2edb891a4d8b02a0b6d151196c477"

      def install
        bin.install "cidr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clok/cidr/releases/download/v0.1.0/cidr_0.1.0_linux_arm64.tar.gz"
      sha256 "970a8957f386d262c47675d7a7d0334a3ae03c5e74c09ed15c49ea0c530b7502"

      def install
        bin.install "cidr"
      end
    end
  end

  test do
    system "#{bin}/cidr --help"
  end
end
