# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cidr < Formula
  desc "CLI tool for checking IPs against CIDR blocks"
  homepage "https://clokwork.net/cidr/"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/clok/cidr/releases/download/v0.0.3/cidr_0.0.3_darwin_amd64.tar.gz"
      sha256 "916ee3d481b020509f8709090d4ea560fe371f06bb38b4cf756d10b06e275bb6"

      def install
        bin.install "cidr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/clok/cidr/releases/download/v0.0.3/cidr_0.0.3_darwin_arm64.tar.gz"
      sha256 "511f981cd42e78aa5c8cd5be526eeb27cd1aff6def7532e73b48737d46628164"

      def install
        bin.install "cidr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/clok/cidr/releases/download/v0.0.3/cidr_0.0.3_linux_arm64.tar.gz"
      sha256 "b4966035cdff68f1c22b5e2e03fee4f61ff203aeae20656befa4eb755c49516e"

      def install
        bin.install "cidr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/clok/cidr/releases/download/v0.0.3/cidr_0.0.3_linux_armv6.tar.gz"
      sha256 "61c6a16fe20885fea50a2c2c9828bb069cf981c8d961d851a550f8badbe71716"

      def install
        bin.install "cidr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/clok/cidr/releases/download/v0.0.3/cidr_0.0.3_linux_amd64.tar.gz"
      sha256 "3f0270644c05e79d3cde53a40db1af9610cea97b2acbc6ae08393611869f12e9"

      def install
        bin.install "cidr"
      end
    end
  end

  test do
    system "#{bin}/cidr --help"
  end
end
